spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/syncfit
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
logging:
  level:
    org.hibernate.SQL: debug